spring:
  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  r2dbc:
    name: ${DATABASE_NAME}
    url: r2dbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    properties:
      ssl: true
      sslMode: REQUIRE
